baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Lambros Petrou"
theme = "minimo-lp"

Paginate = 50
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

[params.copyright]
prefix = ""
holder = "Lambros Petrou"
startYear = "2019"
suffix = ""

[permalinks]
pages = "/:slug/" # for anything under `content/pages`

[params]
mainSections = ["articles"]

[params.settings]
accentColor = "#920000"
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, January 02"
listDateFormat = "2006-01-02"
archiveDateFormat = "2006, Jan 02"
hideEntryNavigation = ["pages"] # boolean / array of sections
hideEntryMeta = ["pages"] # boolean / array of sections
showReadingTime = true
showLastmod = true
hideMainMenu = false
rtl = false

[params.opengraph.twitter]
page = "lambrospetrou" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.comments]
enable = false

[blackfriday]
hrefTargetBlank = true

[taxonomies]
tag = "tags"
